### ISSUE TITLE
cargo generated projects depends on both git and v0.11

### ISSUE THREAD

**Issue by elbaro** [aya-rs/aya#568]
The issue is similar to https://github.com/aya-rs/aya/issues/498 .
Following the guide, cargo-generated projects didn't work out of the box.
This was fixed by updating all aya-* packages to the git.

```
# aya = { version = ">=0.11", features = ["async_tokio"] }

aya = { git = "https://github.com/aya-rs/aya", branch = "main", features = [
    "async_tokio",
] }
```

**Comment by vadorovsky** [comment]
Can you post the error you are getting, please?

We are using releases for user-space crates and git for eBPF crates. And that combination usually works (we are testing it in aya-template CI).

**Comment by elbaro** [comment]
no compile error. uprobe + aya-log prints nothing.

```toml
# aya = { version = ">=0.11", features = ["async_tokio"] }
# aya-log = "0.1"
aya = { git = "https://github.com/aya-rs/aya", branch = "main", features = [
    "async_tokio",
] }
aya-log = { git = "https://github.com/aya-rs/aya", branch = "main" }
```

```rs
#[uprobe(name=..)] pub fn ..() { aya_log_ebpf::info!(&ctx, "enter");}
#[uretprobe(name=..)] pub fn ..() { aya_log_ebpf::info!(&ctx, "exit");}
```
